name: Version Branch Push
on:
  push:
    branches:
      - 'v[0-9]*\.[0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Scan Severity Keyword
        id: check-severity
        env:
          Greeting: Hello
          commitMsg: ${{ github.event.head_commit.message }}
        run: |
          if [[ $commitMsg == *"CRITICAL"* ]]; then
            echo "severity=CRITICAL" >> "$GITHUB_OUTPUT"
          else
            echo "severity=HIGH" >> "$GITHUB_OUTPUT"
          fi
        
      - name: Run Trivy vulnerability scanner
        id: scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: ${{ steps.check-severity.outputs.severity }}
          output: 'trivy-output.txt'

      - name: Slack Notification Failed
        if: always() &&  (steps.scan.outcome == 'failure')
        uses: rtCamp/action-slack-notify@v2
        env:
          # SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_TEST }}
          SLACK_MESSAGE: 'Failed trivy scan, see report for details'
          
      - name: Upload output.txt
        if: always() && (steps.scan.outcome == 'failure')
        uses: adrey/slack-file-upload-action@master
        with:
          # token: ${{ secrets.SLACK_TOKEN }}
          path: trivy-output.txt
          channel: test-submission

      # - name: Build an image from Dockerfile
      #   run: |
      #     docker build -t zhengdocka/dipsa_cicd_workshop/fortunes:${{ github.sha }} .    

      # - run: cat trivy-output.txt
      #   if: ${{ always() }}

