name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Trivy vulnerability scanner
        id: scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'zhengdocka/dipsa_cicd_workshop/fortunes:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH'
          output: 'trivy-output.txt'

      - name: Slack Notification Failed
        if: steps.scan.outcome != 'success'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_TEST }}
          SLACK_MESSAGE: 'Failed trivy scan, see report for details'
          
      - name: Upload output.txt
        if: steps.scan.outcome != 'success'
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: trivy-output.txt
          channel: test-submission

      - name: Build an image from Dockerfile
        run: |
          docker build -t zhengdocka/dipsa_cicd_workshop/fortunes:${{ github.sha }} .    

      - run: cat trivy-output.txt
        if: ${{ always() }}

